// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxiQS-GujUJ0YyYEoqwe5fHqDCM1Hecw',
    appId: '1:35041699528:web:6c954c5dfd8ec8d90f27fd',
    messagingSenderId: '35041699528',
    projectId: 'sabujak-74dbb',
    authDomain: 'sabujak-74dbb.firebaseapp.com',
    storageBucket: 'sabujak-74dbb.firebasestorage.app',
    measurementId: 'G-NVRF5J35EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Bug_DxK0ZGiXXodEhYfD8CDWwYCXftM',
    appId: '1:35041699528:android:5c04dd2fb2f6e3c20f27fd',
    messagingSenderId: '35041699528',
    projectId: 'sabujak-74dbb',
    storageBucket: 'sabujak-74dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJ5ufEtdBbB3QgBWrWlZzJ7_SXze16jw',
    appId: '1:35041699528:ios:6864224508a3d9370f27fd',
    messagingSenderId: '35041699528',
    projectId: 'sabujak-74dbb',
    storageBucket: 'sabujak-74dbb.firebasestorage.app',
    iosBundleId: 'com.example.elpoBookProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJ5ufEtdBbB3QgBWrWlZzJ7_SXze16jw',
    appId: '1:35041699528:ios:6864224508a3d9370f27fd',
    messagingSenderId: '35041699528',
    projectId: 'sabujak-74dbb',
    storageBucket: 'sabujak-74dbb.firebasestorage.app',
    iosBundleId: 'com.example.elpoBookProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxiQS-GujUJ0YyYEoqwe5fHqDCM1Hecw',
    appId: '1:35041699528:web:128d320bbadb5ff70f27fd',
    messagingSenderId: '35041699528',
    projectId: 'sabujak-74dbb',
    authDomain: 'sabujak-74dbb.firebaseapp.com',
    storageBucket: 'sabujak-74dbb.firebasestorage.app',
    measurementId: 'G-RLY4SFLL99',
  );

}